### ISSUE TITLE
More detailed comments on examples

### ISSUE THREAD

**Issue by Ondra09** [bennn/syntax-parse-example#15]
Hi Benn, would it be possible to add more detailed comment for individual lines?

It is hard for beginner to know what exactly is going there.

e.g. in first-class-or macro: 

```
[(_ ?a . ?b)
#'(let ([a-val ?a])
(if a-val a-val (first-class-or . ?b)))]


```

I can't find even a documentation for what `.` means, I can only guess... looking for `.` in docs is not working for me.

Thanks a lot.
Ondrej

**Comment by bennn** [comment]
Hi!

Yes .... we can add more details. It's just hard to know what's the right level of detail. For now I have some ideas about this `.` question and I'll post a pull request "today" about:

- `.`
- `...`
- names that start with `?`
- the general shape of things inside a `syntax-parse`

Please reply or open issues if you think of more things

- - -

To answer about `.` right now .... the `.` is part of the pattern `(_ ?a . ?b)`, and the whole pattern means "I expect a list with at least 2 elements, where
- the first element gets bound to `_` and forgotten
- the second gets bound to the name `?a`
- and the rest of the elements get packed into a list and bound to `?b`"

The official docs for `.` are [here](http://docs.racket-lang.org/syntax/stxparse-patterns.html#%28tech._syntax._pattern%29). This isn't a good page for beginners.

I learned about `.` through the syntax for functions that take any number of arguments, see [`lambda`](http://docs.racket-lang.org/reference/lambda.html?q=lambda#%28form._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._lambda%29%29) & look for `rest-id`

**Comment by bennn** [comment]
> it looks like ... ellipse works as well? Personal preference?

Yes `...` would work there, and yes that was personal preference

> and no . before bind* recursive call... When I tried to add it there I got compiler error. What is the difference there?

There's no `.` because `bind*` refers to a list and `let-star` expects a list in that position.

A `...` can only appear in a syntax object if there's a matching `...` in a pattern. (I hope this makes sense, if not try to play with some small examples.)

You might also want to see this guide section about dot notation in Racket [link](http://docs.racket-lang.org/guide/Pairs__Lists__and_Racket_Syntax.html). Maybe this helps too:

```
Welcome to Racket v7.0.0.2.
> '(1 2 3)
'(1 2 3)
> '(1 . (2 . (3 . ())))
'(1 2 3)
> '(1 . (2 3))
'(1 2 3)
> '(1 . 2 3)
; readline-input:3:4: read-syntax: illegal use of `.` [,bt for context]
```

> I also have some problems in get-macroed with #%datum, expecting it is some way how to "return" value from macro.

The idea is, `get-macroed` produces some syntax that looks just like it would if the value had been written in the source code.

The `.` there is making a pair (just like how `(cons 1 2)` makes a pair)

Here's the docs on [`#%datum`](https://docs.racket-lang.org/reference/quote.html#%28form._%28%28quote._~23~25kernel%29._~23~25datum%29%29)

**Comment by bennn** [comment]
ok, I pushed a quick update in https://github.com/bennn/syntax-parse-example/commit/0751288493904c74c8a0738fc3776ed85f02be26

comments welcome

**Comment by Ondra09** [comment]
Hi, 

so finally, I read through `4.4 def` macro...

**Comment by Ondra09** [comment]
I forgot. In https://docs.racket-lang.org/syntax/stxparse-specifying.html?q=syntax%2Fparse there is an example `(define-syntax-class table ...` which does not work for me. In docs there is ```

> (syntax-parse #'((a 3) (b 2) (c 1))    [t:table     #'(t.sorted-kv ...)]) | > (syntax-parse #'((a 3) (b 2) (c 1)) | [t:table | #'(t.sorted-kv ...)])
-- | -- | -- | --
> (syntax-parse #'((a 3) (b 2) (c 1))
[t:table
#'(t.sorted-kv ...)])
sorting!
#<syntax:6:0 ((c 1) (b 2) (a 3))>
```

but my result is ```sorting!
sorting!
sorting!``` Might this be error in docs?

**Comment by bennn** [comment]
Hi,

Thanks very much for the comments on `def`. I will add some clarifications within the week.

About the docs for `(define-syntax-class table ...`, can you show me the program you're running?

I tried this program:

```
#lang racket/base
(require syntax/parse racket/promise)

(define-syntax-class table
    (pattern ((key value) ...)
             #:attr hashtable
                    (for/hash ([k (syntax->datum #'(key ...))]
                               [v (syntax->datum #'(value ...))])
                      (values k v))
             #:attr [sorted-kv 1]
                    (delay
                     (printf "sorting!\n")
                     (sort (syntax->list #'((key value) ...))
                           <
                           #:key (lambda (kv) (cadr (syntax->datum kv)))))))

(syntax-parse #'((a 3) (b 2) (c 1))
    [t:table
     #'(t.key ...)])

(syntax-parse #'((a 3) (b 2) (c 1))
    [t:table
     #'(t.sorted-kv ...)])
```

Running on the command line (`racket table.rkt`) it prints this:

```
#<syntax:table.rkt:19:7 (a b c)>
sorting!
#<syntax:table.rkt:23:7 ((c 1) (b 2) (a 3))>
```

And if I open Dr Racket (v6.11) and run, I get the same thing.

Maybe the extra prints will go away if you run `raco setup` on the command-line to make sure your syntax & drracket libraries are compiled?


P.S. the docs for `define-syntax-class` are made by actually running the code ([link](https://github.com/racket/racket/blob/master/pkgs/racket-doc/syntax/scribblings/parse/stxclasses.scrbl#L396)), so if they were wrong it would be a deep issue.

**Comment by Ondra09** [comment]
Your code runs as expected in Racket v6.12

This one not:
```
#lang racket

(require rackunit
         (for-syntax racket/base syntax/parse racket/promise))

(begin-for-syntax
  
  (define-syntax-class table
    (pattern ((key value) ...)
             #:attr hashtable             
                    (for/hash ([k (syntax->datum #'(key ...))]
                               [v (syntax->datum #'(value ...))])
                      (values k v))
             #:attr [sorted-kv 1]
                    (delay
                     (printf "sorting!\n")
                     (sort (syntax->list #'((key value) ...))
                           <
                           #:key (lambda (kv) (cadr (syntax->datum kv)))))))

  (syntax-parse #'((a 3) (b 2) (c 1))
    [t:table
     #'(t.key ...)])

  (syntax-parse #'((a 3) (b 2) (c 1))
    [t:table
     #'(t.sorted-kv ...)]))```

**Comment by bennn** [comment]
Ok, that's probably because Dr Racket expands the macros in file more than once.

I'm not sure why Dr Racket does that (for errortrace? to draw the check-syntax arrows?) or if its documented. But if I run that file on the command line I only see one print.

**Comment by Ondra09** [comment]
I don't have much to add for the rest. Should I close this?
